CREATE TABLE `MONGODB.SALES` (
   SALES_ID INT,
   QUANTITY_SOLD DOUBLE,
   AMOUNT_SOLD DOUBLE,
   CHANNEL_DESC STRING,
   PROD_NAME STRING,
   PROD_DESC STRING,
   CUST_FIRST_NAME STRING,
   CUST_LAST_NAME STRING,
   PROMO_NAME STRING,
   PROMO_TOTAL STRING,
   PRIMARY KEY (SALES_ID) NOT ENFORCED
)
DISTRIBUTED BY (SALES_ID) INTO 6 BUCKETS
WITH (
  'changelog.mode' = 'upsert',
  'kafka.cleanup-policy' = 'compact',
  'value.format' = 'avro-registry'
);

INSERT INTO `MONGODB.SALES` (
   SALES_ID,
   QUANTITY_SOLD,
   AMOUNT_SOLD,
   CHANNEL_DESC,
   PROD_NAME,
   PROD_DESC,
   CUST_FIRST_NAME,
   CUST_LAST_NAME,
   PROMO_NAME,
   PROMO_TOTAL)
SELECT
  SLS.SALES_ID,
  SLS.QUANTITY_SOLD,
  SLS.AMOUNT_SOLD,
  CHANNEL_DESC,
  PRD.PROD_NAME,
  PRD.PROD_DESC,
  CUST.CUST_FIRST_NAME,
  CUST.CUST_LAST_NAME,
  PROMO.PROMO_NAME,
  PROMO.PROMO_TOTAL
FROM `ORCLPDB1.SALES.SALES` SLS
JOIN `ORCLPDB1.SALES.CHANNELS` CHN ON SLS.CHANNEL_ID = CHN.CHANNEL_ID
JOIN `ORCLPDB1.SALES.PRODUCTS` PRD ON SLS.PROD_ID = PRD.PROD_ID
JOIN `ORCLPDB1.SALES.CUSTOMERS` CUST ON SLS.CUST_ID = CUST.CUST_ID
LEFT OUTER JOIN `ORCLPDB1.SALES.PROMOTIONS` PROMO ON SLS.PROMO_ID = PROMO.PROMO_ID
;
